### PR TITLE
[claygl] Remove tonemapping, set exposure to 0 when parsing HDR.

### PR DESCRIPTION
**Pull request by pissang**

### CODE REVIEW

**Comment by vorg** [comment]
Overexposure is gone!

1. What does the 'exposure > 0` do then?

2. There is a cubemap seam..

screen shot 2018-03-28 at 09 25 00

**Comment by vorg** [comment]
I also updated to advanced renderer and there are some new issues:

3. SSAO doesn't update as I move the camera



4. I can see temporal antialiasing accumulation phase? I tried to set temporalSuperSampling to false but it doesn't help.

screen shot 2018-03-28 at 09 31 12

**Comment by pissang** [comment]
Great to hear that!

1. `exposure > 0` will adjust the exposure offset when parsing RGBE format data from HDR texture. The code: https://github.com/pissang/claygl/blob/master/src/util/hdr.js#L9 

2. I can't reproduce this bug on my computer. But I think the white seam is caused because I use a sphere to render the panorama environment and there is a precision issue when creating the sphere geometry. I've changed it to cube in the commit https://github.com/pissang/claygl/commit/7add72f7e856065791d0d6307bd8e7c721e8699f and it should be fixed in the next version.

**Comment by pissang** [comment]
I made a new pull request https://github.com/vorg/pbr-compare/pull/2 to solve issues 3, 4.

Issue 3 is caused by wrong velocity buffer. It is fixed in the ClayGL 1.1.3 

Also `autoRender: false` should be added and `graphic` should be removed in the parameter of  `application.create` when using claygl-advanced-renderer.

I think it's correct now:)

screen shot 2018-03-28 at 10 54 39 pm

**Pull request merged**
